package com.zuxt.pingtag.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.*;

public class ConfigScreen {

    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.create(Config.HANDLER, (defaults, config, builder) -> builder
                .title(Component.literal("PingTag Config"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("General"))

                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Conditions"))
                                .description(OptionDescription.of(Component.literal("Condition/toggle settings for the ping nametag.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Enable"))
                                        .description(OptionDescription.of(Component.literal("Toggle the ping nametag display.")))
                                        .binding(defaults.enabled, () -> config.enabled, val -> config.enabled = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Hide When Sneaking"))
                                        .description(OptionDescription.of(Component.literal("Hide ping nametag when the player is sneaking.")))
                                        .binding(defaults.hideWhenSneaking, () -> config.hideWhenSneaking, val -> config.hideWhenSneaking = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Hide If Zero"))
                                        .description(OptionDescription.of(Component.literal("Hide ping nametag if the ping value is zero.")))
                                        .binding(defaults.hideIfZero, () -> config.hideIfZero, val -> config.hideIfZero = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Values"))
                                .description(OptionDescription.of(Component.literal("Value settings for the ping nametag.")))
                                .option(Option.<String>createBuilder()
                                        .name(Component.literal("Prefix Text"))
                                        .description(OptionDescription.of(Component.literal("Text to display before the ping value.")))
                                        .binding(defaults.prefix, () -> config.prefix, val -> config.prefix = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<String>createBuilder()
                                        .name(Component.literal("Suffix Text"))
                                        .description(OptionDescription.of(Component.literal("Text to display after the ping value.")))
                                        .binding(defaults.suffix, () -> config.suffix, val -> config.suffix = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.literal("Y Offset"))
                                        .description(OptionDescription.of(Component.literal("Vertical offset between the player's nametag and the ping nametag.")))
                                        .binding(defaults.offset, () -> config.offset, val -> config.offset = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.00, 0.50)
                                                .step(0.01))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.literal("Scale"))
                                        .description(OptionDescription.of(Component.literal("Scale of the ping nametag relative to the player's nametag.")))
                                        .binding(defaults.nametagScale, () -> config.nametagScale, val -> config.nametagScale = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.5, 1.0)
                                                .step(0.01))
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.literal("Colors"))

                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Text"))

                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Override Prefix Color"))
                                        .description(OptionDescription.of(Component.literal("Override the prefix's color on the ping nametag.")))
                                        .binding(defaults.overridePrefixColor, () -> config.overridePrefixColor, val -> config.overridePrefixColor = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("Prefix Color"))
                                        .description(OptionDescription.of(Component.literal("Color of the prefix text.")))
                                        .binding(defaults.prefixColor, () -> config.prefixColor, val -> config.prefixColor = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Override Suffix Color"))
                                        .description(OptionDescription.of(Component.literal("Override the suffix's color on the ping nametag.")))
                                        .binding(defaults.overrideSuffixColor, () -> config.overrideSuffixColor, val -> config.overrideSuffixColor = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("Suffix Color"))
                                        .description(OptionDescription.of(Component.literal("Color of the suffix text.")))
                                        .binding(defaults.suffixColor, () -> config.suffixColor, val -> config.suffixColor = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Ping"))

                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("0 – 50ms"))
                                        .description(OptionDescription.of(Component.literal("Ping color for 0–50ms.")))
                                        .binding(defaults.pingColorLow, () -> config.pingColorLow, val -> config.pingColorLow = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("51 – 100ms"))
                                        .description(OptionDescription.of(Component.literal("Ping color for 51–100ms.")))
                                        .binding(defaults.pingColorMedium, () -> config.pingColorMedium, val -> config.pingColorMedium = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("101 – 150ms"))
                                        .description(OptionDescription.of(Component.literal("Ping color for 101–150ms.")))
                                        .binding(defaults.pingColorHigh, () -> config.pingColorHigh, val -> config.pingColorHigh = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("151 – 200ms"))
                                        .description(OptionDescription.of(Component.literal("Ping color for 151–200ms.")))
                                        .binding(defaults.pingColorVeryHigh, () -> config.pingColorVeryHigh, val -> config.pingColorVeryHigh = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.literal("200ms+"))
                                        .description(OptionDescription.of(Component.literal("Ping color for 200ms and above.")))
                                        .binding(defaults.pingColorExtreme, () -> config.pingColorExtreme, val -> config.pingColorExtreme = val)
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(false))
                                        .build())
                                .build())
                        .build())
        ).generateScreen(parent);
    }
}